# Generated by Django 5.1.7 on 2025-03-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscribed_at',
            new_name='date_subscribed',
        ),
    ]
