# Generated by Django 5.2.12 on 2026-03-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_mission_activity_usermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='Qualification Phase', max_length=100)),
                ('end_date', models.DateTimeField()),
                ('qualification_points', models.IntegerField(default=1000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
